export const fakeUsers = [
  {
    id: 1,
    firstName: "Terry",
    lastName: "Medhurst",
    username: "atuny0",
    password: "9uQFF1Lh",
  },
  {
    id: 2,
    firstName: "Sheldon",
    lastName: "Quigley",
    username: "hbingley1",
    password: "CQutx25i8r",
  },
  {
    id: 3,
    firstName: "Terrill",
    lastName: "Hills",
    username: "rshawe2",
    password: "OWsTbMUgFc",
  },
  {
    id: 4,
    firstName: "Miles",
    lastName: "Cummerata",
    username: "yraigatt3",
    password: "sRQxjPfdS",
  },
  {
    id: 5,
    firstName: "Mavis",
    lastName: "Schultz",
    username: "kmeus4",
    password: "aUTdmmmbH",
  },
  {
    id: 6,
    firstName: "Alison",
    lastName: "Reichert",
    username: "jtreleven5",
    password: "zY1nE46Zm",
  },
  {
    id: 7,
    firstName: "Oleta",
    lastName: "Abbott",
    username: "dpettegre6",
    password: "YVmhktgYVS",
  },
  {
    id: 8,
    firstName: "Ewell",
    lastName: "Mueller",
    username: "ggude7",
    password: "MWwlaeWcOoF6",
  },
  {
    id: 9,
    firstName: "Demetrius",
    lastName: "Corkery",
    username: "nloiterton8",
    password: "HTQxxXV9Bq4",
  },
  {
    id: 10,
    firstName: "Eleanora",
    lastName: "Price",
    username: "umcgourty9",
    password: "i0xzpX",
  },
  {
    id: 11,
    firstName: "Marcel",
    lastName: "Jones",
    username: "acharlota",
    password: "M9lbMdydMN",
  },
  {
    id: 12,
    firstName: "Assunta",
    lastName: "Rath",
    username: "rhallawellb",
    password: "esTkitT1r",
  },
  {
    id: 13,
    firstName: "Trace",
    lastName: "Douglas",
    username: "lgribbinc",
    password: "ftGj8LZTtv9g",
  },
  {
    id: 14,
    firstName: "Enoch",
    lastName: "Lynch",
    username: "mturleyd",
    password: "GyLnCB8gNIp",
  },
  {
    id: 15,
    firstName: "Jeanne",
    lastName: "Halvorson",
    username: "kminchelle",
    password: "0lelplR",
  },
  {
    id: 16,
    firstName: "Trycia",
    lastName: "Fadel",
    username: "dpierrof",
    password: "Vru55Y4tufI4",
  },
  {
    id: 17,
    firstName: "Bradford",
    lastName: "Prohaska",
    username: "vcholdcroftg",
    password: "mSPzYZfR",
  },
  {
    id: 18,
    firstName: "Arely",
    lastName: "Skiles",
    username: "sberminghamh",
    password: "cAjfb8vg",
  },
  {
    id: 19,
    firstName: "Gust",
    lastName: "Purdy",
    username: "bleveragei",
    password: "UZGAiqPqWQHQ",
  },
  {
    id: 20,
    firstName: "Lenna",
    lastName: "Renner",
    username: "aeatockj",
    password: "szWAG6hc",
  },
  {
    id: 21,
    firstName: "Doyle",
    lastName: "Ernser",
    username: "ckensleyk",
    password: "tq7kPXyf",
  },
  {
    id: 22,
    firstName: "Tressa",
    lastName: "Weber",
    username: "froachel",
    password: "rfVSKImC",
  },
  {
    id: 23,
    firstName: "Felicity",
    lastName: "O'Reilly",
    username: "beykelhofm",
    password: "zQwaHTHbuZyr",
  },
  {
    id: 24,
    firstName: "Jocelyn",
    lastName: "Schuster",
    username: "brickeardn",
    password: "bMQnPttV",
  },
  {
    id: 25,
    firstName: "Edwina",
    lastName: "Ernser",
    username: "dfundello",
    password: "k9zgV68UKw8m",
  },
  {
    id: 26,
    firstName: "Griffin",
    lastName: "Braun",
    username: "lgronaverp",
    password: "4a1dAKDv9KB9",
  },
  {
    id: 27,
    firstName: "Piper",
    lastName: "Schowalter",
    username: "fokillq",
    password: "xZnWSWnqH",
  },
  {
    id: 28,
    firstName: "Kody",
    lastName: "Terry",
    username: "xisherwoodr",
    password: "HLDqN5vCF",
  },
  {
    id: 29,
    firstName: "Macy",
    lastName: "Greenfelder",
    username: "jissetts",
    password: "ePawWgrnZR8L",
  },
  {
    id: 30,
    firstName: "Maurine",
    lastName: "Stracke",
    username: "kdulyt",
    password: "5t6q4KC7O",
  },
  {
    id: 31,
    firstName: "Luciano",
    lastName: "Sauer",
    username: "smargiottau",
    password: "pSGvhgS2A",
  },
  {
    id: 32,
    firstName: "Kaya",
    lastName: "Emard",
    username: "lskeelv",
    password: "Eolj9Svg28",
  },
  {
    id: 33,
    firstName: "Lee",
    lastName: "Schmidt",
    username: "gsilcockw",
    password: "AI6RmBSXjw2S",
  },
  {
    id: 34,
    firstName: "Darien",
    lastName: "Witting",
    username: "aaughtonx",
    password: "Vzwc72RhNGu",
  },
  {
    id: 35,
    firstName: "Jacklyn",
    lastName: "Schimmel",
    username: "mbrooksbanky",
    password: "9V8lqrkq",
  },
  {
    id: 36,
    firstName: "Angelica",
    lastName: "Baumbach",
    username: "dalmondz",
    password: "wM5tOHRMQt6g",
  },
  {
    id: 37,
    firstName: "Delfina",
    lastName: "Ziemann",
    username: "nwytchard10",
    password: "ij8mFevk",
  },
  {
    id: 38,
    firstName: "Thaddeus",
    lastName: "McCullough",
    username: "igannan11",
    password: "MB63jkg3W",
  },
  {
    id: 39,
    firstName: "Salvatore",
    lastName: "Fisher",
    username: "lgherardi12",
    password: "m0eNOs",
  },
  {
    id: 40,
    firstName: "Jasmin",
    lastName: "Hermiston",
    username: "lgutridge13",
    password: "SqR03CE",
  },
  {
    id: 41,
    firstName: "Nicklaus",
    lastName: "Cruickshank",
    username: "cslateford14",
    password: "wpbWfIbpIgGc",
  },
  {
    id: 42,
    firstName: "Tiara",
    lastName: "Rolfson",
    username: "mhaslegrave15",
    password: "sq5FYgvU",
  },
  {
    id: 43,
    firstName: "Garret",
    lastName: "Klocko",
    username: "kbrecknock16",
    password: "KoNiIBiHE",
  },
  {
    id: 44,
    firstName: "Reginald",
    lastName: "Wisoky",
    username: "rlaxe17",
    password: "OHFibd",
  },
  {
    id: 45,
    firstName: "Humberto",
    lastName: "Botsford",
    username: "pidill18",
    password: "GbBDdjbKG1a2",
  },
  {
    id: 46,
    firstName: "Justus",
    lastName: "Sipes",
    username: "rmcritchie19",
    password: "QFSwkjeVEhOQ",
  },
  {
    id: 47,
    firstName: "Coralie",
    lastName: "Boyle",
    username: "rlangston1a",
    password: "rU8ybew",
  },
  {
    id: 48,
    firstName: "Felicita",
    lastName: "Gibson",
    username: "jevanson1b",
    password: "1Dlvqluwi5zO",
  },
  {
    id: 49,
    firstName: "Pearl",
    lastName: "Blick",
    username: "ssarjant1c",
    password: "y2YBSxtcmXVW",
  },
  {
    id: 50,
    firstName: "Johnathon",
    lastName: "Predovic",
    username: "xlinster1d",
    password: "WHAE1AtmDh",
  },
  {
    id: 51,
    firstName: "Jerry",
    lastName: "Kertzmann",
    username: "tmullender1e",
    password: "fxJRvUVCFA95",
  },
  {
    id: 52,
    firstName: "Elbert",
    lastName: "Gottlieb",
    username: "gmein1f",
    password: "VYaG1Ew",
  },
  {
    id: 53,
    firstName: "Sincere",
    lastName: "Mueller",
    username: "gmaccumeskey1g",
    password: "bETj6uCOI",
  },
  {
    id: 54,
    firstName: "Telly",
    lastName: "Spinka",
    username: "bpetts1h",
    password: "IxI5sjpNT5F",
  },
  {
    id: 55,
    firstName: "Hal",
    lastName: "Keebler",
    username: "ajozef1i",
    password: "uAVFvWB0Pxi",
  },
  {
    id: 56,
    firstName: "Megane",
    lastName: "Armstrong",
    username: "oyakushkev1j",
    password: "UB3BAOn8Sj7",
  },
  {
    id: 57,
    firstName: "Toy",
    lastName: "Olson",
    username: "bpickering1k",
    password: "J4f0Es7sxXVO",
  },
  {
    id: 58,
    firstName: "Deanna",
    lastName: "Glover",
    username: "nworley1l",
    password: "HhWAr5TR",
  },
  {
    id: 59,
    firstName: "Marcella",
    lastName: "Shanahan",
    username: "klife1m",
    password: "ZdEndJIQLM",
  },
  {
    id: 60,
    firstName: "Rachel",
    lastName: "Jacobson",
    username: "dlambarth1n",
    password: "1zosSj9eR",
  },
  {
    id: 61,
    firstName: "Nora",
    lastName: "Sawayn",
    username: "cepgrave1o",
    password: "BnC5P3MdJ",
  },
  {
    id: 62,
    firstName: "Mozell",
    lastName: "O'Connell",
    username: "mpoyner1p",
    password: "nCTH1QhLCNY",
  },
  {
    id: 63,
    firstName: "Nasir",
    lastName: "Leuschke",
    username: "eburras1q",
    password: "Y7UmdaATt",
  },
  {
    id: 64,
    firstName: "Quinn",
    lastName: "Witting",
    username: "gfernandes1r",
    password: "LzI2Plmj",
  },
  {
    id: 65,
    firstName: "Jeanne",
    lastName: "O'Keefe",
    username: "hollet1s",
    password: "WK46QB",
  },
  {
    id: 66,
    firstName: "Terrence",
    lastName: "Koelpin",
    username: "hfasey1t",
    password: "vDMcOSFj0",
  },
  {
    id: 67,
    firstName: "Davonte",
    lastName: "Heaney",
    username: "gbarhams1u",
    password: "uDO326b3Hn7O",
  },
  {
    id: 68,
    firstName: "Everette",
    lastName: "Prohaska",
    username: "rstrettle1v",
    password: "ryhdXB",
  },
  {
    id: 69,
    firstName: "Oda",
    lastName: "Schmidt",
    username: "btegler1w",
    password: "xx9O9fzZI",
  },
  {
    id: 70,
    firstName: "Twila",
    lastName: "Padberg",
    username: "cmasurel1x",
    password: "es8eVhVy4c",
  },
  {
    id: 71,
    firstName: "Amelia",
    lastName: "Mann",
    username: "omarsland1y",
    password: "MT463NsEI",
  },
  {
    id: 72,
    firstName: "Frederique",
    lastName: "Boehm",
    username: "mcrumpe1z",
    password: "F8JxU31tNw",
  },
  {
    id: 73,
    firstName: "Clotilde",
    lastName: "Larson",
    username: "wfeldon20",
    password: "cLcJUmA",
  },
  {
    id: 74,
    firstName: "Moriah",
    lastName: "Mills",
    username: "ahinckes21",
    password: "dIoZ2huN",
  },
  {
    id: 75,
    firstName: "Claudia",
    lastName: "Dooley",
    username: "ptilson22",
    password: "jNbmsr",
  },
  {
    id: 76,
    firstName: "Deon",
    lastName: "Gutkowski",
    username: "cgaber23",
    password: "nieEPfUI",
  },
  {
    id: 77,
    firstName: "Amos",
    lastName: "Weimann",
    username: "rkingswood24",
    password: "0VNksmUL7",
  },
  {
    id: 78,
    firstName: "Frankie",
    lastName: "Hudson",
    username: "dbuist25",
    password: "OlP0CIw",
  },
  {
    id: 79,
    firstName: "Harrison",
    lastName: "Lemke",
    username: "pmoraleda26",
    password: "QrZGjkTF8eX",
  },
  {
    id: 80,
    firstName: "Guy",
    lastName: "Franecki",
    username: "vkohrt27",
    password: "yMmUuTZDdPC",
  },
  {
    id: 81,
    firstName: "Sidney",
    lastName: "Rutherford",
    username: "capplewhite28",
    password: "oqqDPsff",
  },
  {
    id: 82,
    firstName: "Maymie",
    lastName: "Yundt",
    username: "kogilvy29",
    password: "aGX6R9Xd9bd2",
  },
  {
    id: 83,
    firstName: "Rita",
    lastName: "Shields",
    username: "gconford2a",
    password: "CNZ3xN",
  },
  {
    id: 84,
    firstName: "Aniya",
    lastName: "Wisozk",
    username: "dmantle2b",
    password: "SBnr789",
  },
  {
    id: 85,
    firstName: "Angelica",
    lastName: "Metz",
    username: "kpondjones2c",
    password: "H4IiV9f8jb",
  },
  {
    id: 86,
    firstName: "Rupert",
    lastName: "Upton",
    username: "whuman2d",
    password: "JyHAUcC",
  },
  {
    id: 87,
    firstName: "Eleazar",
    lastName: "Torp",
    username: "fschlagman2e",
    password: "icEdQz4YnwV",
  },
  {
    id: 88,
    firstName: "Anais",
    lastName: "Yundt",
    username: "agreenhouse2f",
    password: "VmqqWniF",
  },
  {
    id: 89,
    firstName: "Gayle",
    lastName: "Krajcik",
    username: "cdwyr2g",
    password: "x96XD8Fm",
  },
  {
    id: 90,
    firstName: "Wilma",
    lastName: "Hickle",
    username: "omottley2h",
    password: "67oJrJe6ta",
  },
  {
    id: 91,
    firstName: "Arne",
    lastName: "Jacobs",
    username: "hyaknov2i",
    password: "Xw8nIye1",
  },
  {
    id: 92,
    firstName: "Emely",
    lastName: "Schmitt",
    username: "clambol2j",
    password: "MJRFJutRGS",
  },
  {
    id: 93,
    firstName: "Fabiola",
    lastName: "Oberbrunner",
    username: "dduggan2k",
    password: "Hf0TgLPXG",
  },
  {
    id: 94,
    firstName: "Kari",
    lastName: "Schinner",
    username: "jtossell2l",
    password: "LTRc4mC",
  },
  {
    id: 95,
    firstName: "Rory",
    lastName: "Conn",
    username: "cchomiszewski2m",
    password: "xjuQsRDR0NP6",
  },
  {
    id: 96,
    firstName: "Cristobal",
    lastName: "Watsica",
    username: "bgoby2n",
    password: "aKzuEqfI3wU",
  },
  {
    id: 97,
    firstName: "Allene",
    lastName: "Harber",
    username: "cdavydochkin2o",
    password: "N1node",
  },
  {
    id: 98,
    firstName: "Lempi",
    lastName: "Runte",
    username: "zstenning2p",
    password: "Ck5jBaO6691g",
  },
  {
    id: 99,
    firstName: "Terrell",
    lastName: "Schuppe",
    username: "flesslie2q",
    password: "XUKU613LscMS",
  },
  {
    id: 100,
    firstName: "Tevin",
    lastName: "Prohaska",
    username: "pcumbes2r",
    password: "obhSsvCF8c0",
  },
];

export const isFakeUser = (username) => {
  for (const user of fakeUsers) {
    if (user.username === username) {
      return true;
    }
  }
  return false;
};

export const checkFakePassword = (username, password) => {
  for (const user of fakeUsers) {
    if (user.username === username && user.password === password) {
      return true;
    }
  }
  return false;
};
